### PR TITLE
Update CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by code-arman**
Created https://github.com/code-arman/Cleanify based off of "A program that takes your spotify playlist and converts it to a clean version with the same songs, and removes it if it can't find any. Used to be able to listen to my playlists in the car with my parents."

### CODE REVIEW

**Comment by Divide-By-0** [comment]
This is awesome! Super impressed at how fast you got it out :) Is there a web frontend for anyone to use it, or is it strictly local right now?

**Comment by code-arman** [comment]
Thanks! Currently it's just local and has instructions on how to run it in the readme file but I may eventually want host it so anyone can use it. I found out that there are some very occasional issues with it timing out on huge playlists so I'll have to fix when I get a chance

**Comment by Divide-By-0** [comment]
Awesome! I've merged for now, but let me know if you'd like some tips for the fastest way to host it :)

**Comment by code-arman** [comment]
> Awesome! I've merged for now, but let me know if you'd like some tips for the fastest/cheapest way to host it :)

Recently rebuilt this project with React and hosted it here: https://www.cleanify.app/!

**Comment by Divide-By-0** [comment]
Whoah -- this looks really good, I'm excited to try this new version! Have you marketed at all on i.e. Reddit?

**Comment by code-arman** [comment]
Thank you! Had a fun time building it. Would love to hear any feedback/suggestions if you have any.

I've posted on a couple smaller subreddits but the bigger ones like r/Spotify require a karma limit. I'll post there once my account gets enough karma lol

**Comment by Divide-By-0** [comment]
I have an account with 10K karma, send over a post you made somewhere else + a list of subreddits and I can post the same thing there?

**Comment by code-arman** [comment]
Thank you for offering this! I made a [post](https://www.reddit.com/r/truespotify/comments/tsd58v/wwwcleanifyapp_made_a_website_to_clean_your/) a couple days ago that got enough traction, so my account should be good on the karma limit now. I'll probably post to the real Spotify subreddit tmmr. If it still doesnt allow me to, I'll let you know. 


Btw, Reddit marketing has definitely been working so far :) (this screenshot comes from my spotify developer dashboard)


 Screen Shot 2022-04-02 at 3 30 43 AM

**Pull request merged**
